import { Slide } from '@/types';

// PPT 内容配置 - 在这里硬编码所有幻灯片内容
export const defaultSlides: Slide[] = [
  {
    id: 1,
    type: 'video',
    url: '/assets/videos/page-1.mp4',
    title: '封面',
  },
  {
    id: 2,
    type: 'video',
    url: '/assets/videos/page-2.mp4',
    title: '导入',
  },
  {
    id: 3,
    type: 'video',
    url: '/assets/videos/page-3.mp4',
    title: '听一听',
  },
  {
    id: 4,
    type: 'video',
    url: '/assets/videos/page-4.mp4',
    title: '学唱',
  },
  {
    id: 5,
    type: 'image',
    url: '/assets/images/page-5.png',
    title: '大象叫声',
  },
  {
    id: 6,
    type: 'video',
    url: '/assets/videos/乌鸦导入.mp4',
    title: '乌鸦导入',
  },
  {
    id: 34,
    type: 'component',
    url: '',
    title: '歌词填空',
  },
  {
    id: 7,
    type: 'image',
    url: '/assets/images/page-7.png',
    title: '曲谱',
  },
  {
    id: 8,
    type: 'image',
    url: '/assets/images/page-8.png',
    title: '八音筒导入',
  },
  {
    id: 9,
    type: 'image',
    url: '/assets/images/page-9.png',
    title: '歌词变图片导入',
  },
  {
    id: 10,
    type: 'video',
    url: '/assets/videos/page-10.mp4',
    title: '歌词1',
  },
  {
    id: 11,
    type: 'video',
    url: '/assets/videos/page-11.mp4',
    title: '歌词2',
  },
  {
    id: 12,
    type: 'video',
    url: '/assets/videos/page-12.mp4',
    title: '歌词3',
  },
  {
    id: 13,
    type: 'video',
    url: '/assets/videos/page-13.mp4',
    title: '歌词4',
  },
  {
    id: 14,
    type: 'video',
    url: '/assets/videos/page-14.mp4',
    title: '歌词5',
  },
  {
    id: 15,
    type: 'video',
    url: '/assets/videos/page-15.mp4',
    title: '歌词6',
  },
  {
    id: 16,
    type: 'video',
    url: '/assets/videos/page-16.mp4',
    title: '歌词7',
  },
  {
    id: 17,
    type: 'video',
    url: '/assets/videos/page-17.mp4',
    title: '歌词8',
  },
  {
    id: 18,
    type: 'image',
    url: '/assets/images/page-18.png',
    title: '弹唱',
  },
  {
    id: 19,
    type: 'image',
    url: '/assets/images/page-19.png',
    title: '图片动起来导入',
  },
  {
    id: 20,
    type: 'video',
    url: '/assets/videos/page-20.mp4',
    title: '歌词1',
  },
  {
    id: 21,
    type: 'video',
    url: '/assets/videos/page-21.mp4',
    title: '歌词2',
  },
  {
    id: 22,
    type: 'video',
    url: '/assets/videos/page-22.mp4',
    title: '歌词3',
  },
  {
    id: 23,
    type: 'video',
    url: '/assets/videos/page-23.mp4',
    title: '歌词4',
  },
  {
    id: 24,
    type: 'video',
    url: '/assets/videos/page-24.mp4',
    title: '歌词5',
  },
  {
    id: 25,
    type: 'video',
    url: '/assets/videos/page-25.mp4',
    title: '歌词6',
  },
  {
    id: 26,
    type: 'video',
    url: '/assets/videos/page-26.mp4',
    title: '歌词7',
  },
  {
    id: 27,
    type: 'video',
    url: '/assets/videos/page-27.mp4',
    title: '歌词8',
  },
  {
    id: 28,
    type: 'video',
    url: '/assets/videos/page-28.mp4',
    title: '乌鸦唱歌导入',
  },
  {
    id: 29,
    type: 'video',
    url: '/assets/videos/page-29.mp4',
    title: '乌鸦合唱团',
  },
  {
    id: 30,
    type: 'image',
    url: '/assets/images/page-30.png',
    title: '想一想',
  },
  {
    id: 33,
    type: 'video',
    url: '/assets/videos/完整带伴奏.mp4',
    title: '完整伴奏',
  },
  {
    id: 31,
    type: 'video',
    url: '/assets/videos/评委.mp4',
    title: '评价',
  },
  {
    id: 32,
    type: 'component',
    url: '',
    title: '激励',
  },
  // 在这里添加更多幻灯片...
];

